name: dependency-updates

on:
  push:
  schedule:
    - cron:  "0 */6 * * *"
  workflow_dispatch:

jobs:
  s6-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update s6 version
        id: update
        run: |
          S6_VERSION="$(
          git ls-remote --tags https://github.com/just-containers/s6-overlay "v1.*" \
              | cut -d/ -f3 \
              | sort -V \
              | tail -1 \
              | sed -E "s/\^\{\}//"
          )"
          sed -i "s|ARG S6_VERSION=.*|ARG S6_VERSION=$S6_VERSION|" ./docker/Dockerfile
          echo "version=$S6_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          signoff: true
          delete-branch: true
          commit-message: update s6 version to ${{ steps.update.outputs.version }}
          branch: update-s6-version
          title: update s6 version to ${{ steps.update.outputs.version }}
          body: update s6 version to ${{ steps.update.outputs.version }}
