name: Docker CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cloudflared.Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/cloudflared:${{ github.ref_name }}

      - name: Build-pagespeed
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pagespeed.Dockerfile
          platforms: linux/amd64 #,linux/arm64 #,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }} , ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}-pagespeed

      - name: Build-pagespeed
        if: github.ref == 'refs/heads/latest'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pagespeed.Dockerfile
          platforms: linux/amd64 #,linux/arm64 #,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:pagespeed

      - name: Build-quici
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./quici.Dockerfile
          platforms: linux/amd64 #,linux/arm64 #,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}-quici

      - name: Build-quici
        if: github.ref == 'refs/heads/latest'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./quici.Dockerfile
          platforms: linux/amd64 #,linux/arm64 #,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:quici
