name: update-and-lint
on:
  push:
    branches:
      - develop
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  update-and-lint:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'develop' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: eslint
        run: |
          cd backend
          yarn install --no-lockfile
          yarn eslint . --fix
      - name: nginxbeautifier
        run: |
          yarn global add nginxbeautifier
          mv -v rootfs/usr/local/nginx/conf/exploits.conf exploits.conf
          nginxbeautifier -s 4 -r rootfs/usr/local/nginx/conf
          mv -v exploits.conf rootfs/usr/local/nginx/conf/exploits.conf
      - name: push changes
        run: |
          git add -A
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -sm "update and lint"
          git push
